name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "include"
          - "src"
          - "tests"
          - "examples"
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "18"
          include-regex: ^.*\.((((c|t|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(ino|pde|proto|cu))$
          check-path: ${{ matrix.path }}
          exclude-regex: ^(eigen_matio\.hpp)|(tl_optional.hpp)$
          fallback-style: Google
